name: marvington_game
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.9.1
  flame_tiled: ^1.14.1
  flame_audio: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Marvington/Marv Fall.png"



flutter:
  uses-material-design: true


  assets:
    - assets/tiles/
    - assets/images/Terrain/
    - assets/images/Background/
    - assets/images/Bullet/
    - assets/images/Items/Checkpoints/Checkpoint/
    - assets/images/Items/Fruits/
    - assets/images/Traps/Moon/
    - assets/images/Traps/Fire/
    - assets/images/Marvington/
    - assets/images/Enemies/Radish/
    - assets/images/Enemies/Blob/
    - assets/images/Enemies/BlueBird/
    - assets/audio/