name: Flutter Web Deployment

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v6
        with:
          flutter-version: '3.13.6'  # Change this to your Flutter version

      - name: Build Flutter Web
        run: flutter build web --base-href="/game/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: build/web
          publish_branch: ghpages
        env:
          CAMEL_CASE_BRANCH: main  # Change this to your main branch

